package eu.avalanche7.paradigm.api;

public enum ApiCapability {
    PERMISSION_CHECKS,
    PERMISSION_NODE_REGISTRATION,
    MESSAGE_DELIVERY_AND_FORMATTING,
    PERMISSION_METADATA,
    EXTERNAL_PLACEHOLDERS
}
