package eu.avalanche7.paradigm.modules.audit;

public enum AuditActionType {
    DASHBOARD_LOGIN,
    DASHBOARD_LOGOUT,
    CONFIG_PATCH,
    COMMAND_TOGGLE,
    COOLDOWN_CHANGE,
    CUSTOM_COMMAND_CHANGE,
    HOLOGRAM_CHANGE,
    STORAGE_TEST,
    STORAGE_MIGRATION_DRY_RUN,
    PERMISSION_CHANGE,
    GROUP_CHANGE,
    MODERATION_ACTION,
    WEBEDITOR_SESSION,
    DASHBOARD_STATUS,
    UNKNOWN
}
