package eu.avalanche7.paradigm.modules.audit;

public enum AuditActionType {
    DASHBOARD_LOGIN,
    DASHBOARD_LOGOUT,
    CONFIG_PATCH,
    COMMAND_TOGGLE,
    COOLDOWN_CHANGE,
    CUSTOM_COMMAND_CHANGE,
    HOLOGRAM_CHANGE,
    MENU_CHANGE,
    STORAGE_TEST,
    STORAGE_MIGRATION_DRY_RUN,
    PERMISSION_CHANGE,
    GROUP_CHANGE,
    MODERATION_ACTION,
    DASHBOARD_STATUS,
    DISCORD_CHANGE,
    DISCORD_TEST,
    DISCORD_CONSOLE_COMMAND,
    REMOTE_CONFIG_PATCH,
    REMOTE_CONFIG_ADOPT,
    TICKET_CHANGE,
    UNKNOWN
}
